"""add carga_horaria_diaria em Turma

Revision ID: 0bb467a0c014
Revises: 5fbeba82e95a
Create Date: 2025-11-28 20:26:02.624394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bb467a0c014'
down_revision = '5fbeba82e95a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turmas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('carga_horaria_diaria', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turmas', schema=None) as batch_op:
        batch_op.drop_column('carga_horaria_diaria')

    # ### end Alembic commands ###
