"""estrutura completa inicial

Revision ID: 5fbeba82e95a
Revises: 
Create Date: 2025-11-27 23:00:30.727610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fbeba82e95a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anos_letivos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=20), nullable=False),
    sa.Column('data_inicio_ano', sa.Date(), nullable=False),
    sa.Column('data_fim_ano', sa.Date(), nullable=False),
    sa.Column('data_fim_semestre1', sa.Date(), nullable=False),
    sa.Column('data_inicio_semestre2', sa.Date(), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('fechado', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('livros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('disciplinas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('sigla', sa.String(length=20), nullable=True),
    sa.Column('ano_letivo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ano_letivo_id'], ['anos_letivos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feriados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ano_letivo_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('data_text', sa.String(length=255), nullable=True),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['ano_letivo_id'], ['anos_letivos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interrupcoes_letivas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ano_letivo_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=True),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('data_text', sa.String(length=255), nullable=True),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['ano_letivo_id'], ['anos_letivos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('turmas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('ano_letivo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ano_letivo_id'], ['anos_letivos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exclusoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('turma_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('data_text', sa.String(length=255), nullable=True),
    sa.Column('motivo', sa.String(length=255), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('extras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('turma_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('data_text', sa.String(length=255), nullable=True),
    sa.Column('motivo', sa.String(length=255), nullable=True),
    sa.Column('aulas', sa.Integer(), nullable=False),
    sa.Column('modulo_nome', sa.String(length=255), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('horarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('turma_id', sa.Integer(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('horas', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('livros_turmas',
    sa.Column('livro_id', sa.Integer(), nullable=False),
    sa.Column('turma_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['livro_id'], ['livros.id'], ),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], ),
    sa.PrimaryKeyConstraint('livro_id', 'turma_id')
    )
    op.create_table('modulos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('turma_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('total_aulas', sa.Integer(), nullable=False),
    sa.Column('tolerancia', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('periodos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('turma_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('turmas_disciplinas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('turma_id', sa.Integer(), nullable=False),
    sa.Column('disciplina_id', sa.Integer(), nullable=False),
    sa.Column('horas_semanais', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['disciplina_id'], ['disciplinas.id'], ),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('turma_id', 'disciplina_id', name='uq_turma_disciplina')
    )
    op.create_table('calendario_aulas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('livro_id', sa.Integer(), nullable=False),
    sa.Column('turma_id', sa.Integer(), nullable=False),
    sa.Column('periodo_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('modulo_nome', sa.String(length=255), nullable=True),
    sa.Column('n_aula_modulo', sa.String(length=50), nullable=True),
    sa.Column('total_aulas', sa.String(length=50), nullable=True),
    sa.Column('n_sumario', sa.String(length=50), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('sumario', sa.Text(), nullable=True),
    sa.Column('tipo_dia', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['livro_id'], ['livros.id'], ),
    sa.ForeignKeyConstraint(['periodo_id'], ['periodos.id'], ),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('calendario_aulas')
    op.drop_table('turmas_disciplinas')
    op.drop_table('periodos')
    op.drop_table('modulos')
    op.drop_table('livros_turmas')
    op.drop_table('horarios')
    op.drop_table('extras')
    op.drop_table('exclusoes')
    op.drop_table('turmas')
    op.drop_table('interrupcoes_letivas')
    op.drop_table('feriados')
    op.drop_table('disciplinas')
    op.drop_table('livros')
    op.drop_table('anos_letivos')
    # ### end Alembic commands ###
