"""add carga horária semanal na turma

Revision ID: c59d534248e0
Revises: 0bb467a0c014
Create Date: 2025-11-28 20:37:01.154938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c59d534248e0'
down_revision = '0bb467a0c014'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turmas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('carga_segunda', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('carga_terca', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('carga_quarta', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('carga_quinta', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('carga_sexta', sa.Float(), nullable=True))
        batch_op.drop_column('carga_horaria_diaria')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turmas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('carga_horaria_diaria', sa.FLOAT(), nullable=True))
        batch_op.drop_column('carga_sexta')
        batch_op.drop_column('carga_quinta')
        batch_op.drop_column('carga_quarta')
        batch_op.drop_column('carga_terca')
        batch_op.drop_column('carga_segunda')

    # ### end Alembic commands ###
